[package]
name = "sleepy-session"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
fs2 = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sleepy-sdk = { git = "https://github.com/sleepylinux/sleepy-sdk", rev = "4c4f7989b957f41f3748ddfb092b0348e2ba9e88" }
uuid = { version = "1.24", features = ["v4"] }

[dev-dependencies]
tempfile = "3.27"
