[package]
name = "sleepy-session"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
fs2 = "0.4"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sleepy-sdk = { git = "https://github.com/sleepylinux/sleepy-sdk", rev = "5dc792faea9d743fabbb576ae1b25ed7e1f729f9" }
uuid = { version = "1.24", features = ["v4"] }

[dev-dependencies]
tempfile = "3.27"
sha2 = "0.10"
